import os
import tkinter
eliminador_de_virus = False
os.system("md virus_para_EL_ALMA")
os.system("md virus_informatico")
os.system("md diego_pro")
os.system("md algo_ay")
os.system("md hola_mundo")
os.system("md que carajos")
os.system("md hhwshdhhdebncndjvjfjvnvjnhnfnvnfjnvbcnvbdjuvhvirusjfnfjfjgnrjfjdetectadojdjgjrogjkrjgjtjgjtjg")
os.system("md virus_para_EL_ALMA")
os.system("md AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
os.system("md SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOYYYYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUUUNNNNNNNNNNNNNNNNNNNNPPPPPPPPPPPPPPPPPPPPPPPPRRRRRRRRRRRRRRRRRRRRRROOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
os.system("md programado_en_python")
os.system("md Te_infectaste_bobo")
os.system("md weje pc ")
os.system("md se destruira tu pc ")
os.system("cls")
input("crees que este virus destruya tu pc ")
eliminador_de_virus = True
if eliminador_de_virus == True:
    input("pues no ")
os.system("rd virus_para_EL_ALMA")
os.system("rd virus_informatico")
os.system("rd diego_pro")
os.system("rd algo_ay")
os.system("rd hola_mundo")
os.system("rd que carajos")
os.system("rd hhwshdhhdebncndjvjfjvnvjnhnfnvnfjnvbcnvbdjuvhvirusjfnfjfjgnrjfjdetectadojdjgjrogjkrjgjtjgjtjg")
os.system("md AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
os.system("rd SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOYYYYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUUUNNNNNNNNNNNNNNNNNNNNPPPPPPPPPPPPPPPPPPPPPPPPRRRRRRRRRRRRRRRRRRRRRROOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
os.system("rd programado_en_python")
os.system("rd Te_infectaste_bobo")
os.system("rd weje pc ")
os.system("rd se destruira tu pc ")
windows = tkinter.Tk()
windows.title("sean limpiado las amenasas ")
windows.geometry("500x500")
windows.resizable(0,0)
windows.config(bg="blue")
windows.config(bg="yellow")
texto = tkinter.Label(windows, text="sean eliminado las amenasas").pack()
windows.mainloop()
